set(PackName "libfontenc-1.1.4")
message("CMAKE_CURRENT_LIST_DIR : ${CMAKE_CURRENT_LIST_DIR}")
get_filename_component(FONTENC_CMAKE_DIR "${CMAKE_CURRENT_LIST_DIR}/${PackName}" ABSOLUTE)
get_filename_component(FONTENC_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/${PackName}/include" ABSOLUTE)
get_filename_component(FONTENC_LIB_DIR "${CMAKE_CURRENT_LIST_DIR}/${PackName}/lib" ABSOLUTE)


#for xorg-server configure FONTENC_CFLAGS FONTENC_LIBS
message("FONTENC_LIB_DIR : ${FONTENC_LIB_DIR}")

set(FONTENC_CFLAGS "-I${FONTENC_INCLUDE_DIR} ")
set(FONTENC_LIBS "-L${FONTENC_LIB_DIR} -lfontenc ")
message("FONTENC_CFLAGS: ${FONTENC_CFLAGS}")
message("FONTENC_LIBS : ${FONTENC_LIBS}")

string(APPEND XSERVERLIBS_CFLAGS ${FONTENC_CFLAGS})
string(APPEND XSERVERLIBS_LIBS ${FONTENC_LIBS})
string(APPEND XSERVERCFLAGS_CFLAGS ${FONTENC_CFLAGS})
string(APPEND XSERVERCFLAGS_LIBS ${FONTENC_LIBS})

