set(PackName "xorgproto-2020.1")
message("CMAKE_CURRENT_LIST_DIR : ${CMAKE_CURRENT_LIST_DIR}")
get_filename_component(XORGPROTO_CMAKE_DIR "${CMAKE_CURRENT_LIST_DIR}/${PackName}" ABSOLUTE)
get_filename_component(XORGPROTO_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/${PackName}/include" ABSOLUTE)
get_filename_component(XORGPROTO_INCLUDE_DIR_GL "${CMAKE_CURRENT_LIST_DIR}/${PackName}/include/GL" ABSOLUTE)
get_filename_component(XORGPROTO_INCLUDE_DIR_X11 "${CMAKE_CURRENT_LIST_DIR}/${PackName}/include/X11" ABSOLUTE)
get_filename_component(XORGPROTO_INCLUDE_DIR_X11_DRI "${CMAKE_CURRENT_LIST_DIR}/${PackName}/include/X11/dri" ABSOLUTE)

set(XORGPROTO_CFLAGS "-I${XORGPROTO_INCLUDE_DIR} -I${XORGPROTO_INCLUDE_DIR_GL} -I${XORGPROTO_INCLUDE_DIR_X11} -I${XORGPROTO_INCLUDE_DIR_X11_DRI} ")

message("XORGPROTO_CFLAGS: ${XORGPROTO_CFLAGS}")


string(APPEND XSERVERLIBS_CFLAGS ${XORGPROTO_CFLAGS})
string(APPEND XSERVERCFLAGS_CFLAGS ${XORGPROTO_CFLAGS})
