set(PackName "libxshmfence-1.3")
get_filename_component(XSHMFENCE_CMAKE_DIR "${CMAKE_CURRENT_LIST_DIR}/${PackName}" ABSOLUTE)
get_filename_component(XSHMFENCE_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/${PackName}/include" ABSOLUTE)
get_filename_component(XSHMFENCE_LIB_DIR "${CMAKE_CURRENT_LIST_DIR}/${PackName}/lib" ABSOLUTE)


#for xorg-server configure XSHMFENCE_CFLAGS XSHMFENCE_LIBS
message("XSHMFENCE_LIB_DIR : ${XSHMFENCE_LIB_DIR}")

set(XSHMFENCE_CFLAGS "-I${XSHMFENCE_INCLUDE_DIR} ")
set(XSHMFENCE_LIBS "-L${XSHMFENCE_LIB_DIR} -lxshmfence ")
message("XSHMFENCE_CFLAGS: ${XSHMFENCE_CFLAGS}")
message("XSHMFENCE_LIBS : ${XSHMFENCE_LIBS}")

string(APPEND XSERVERLIBS_CFLAGS ${XSHMFENCE_CFLAGS})
string(APPEND XSERVERLIBS_LIBS ${XSHMFENCE_LIBS})
string(APPEND XSERVERCFLAGS_CFLAGS ${XSHMFENCE_CFLAGS})
string(APPEND XSERVERCFLAGS_LIBS ${XSHMFENCE_LIBS})

